[phases.setup]
# Remove "pip" from this list
nixPkgs = ["...", "python312"]

[phases.install]
# You can still use the pip command here; it just can't be in nixPkgs
cmds = ["...", "pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
